# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST: mysql# mysql component service name
# ---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: narendranreddy/frontend:v1.0   
        envFrom:
        - configMapRef:
            name: frontend
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  selector:
    component: frontend
    project: expense
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80