kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: backend
    spec:
      containers:
      - name: backend
        image: narendranreddy/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend       
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense 
spec:
  selector:
    component: backend
    project: expense
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080